
stages:
  - mirror

mirror:toGithub:
  stage: mirror
  image: ${CI_REGISTRY}/utilities/build-images/ubuntu-18-04-build:master
  when: manual
  only:
    - main
  tags:
    - docker
  environment:
    name: github
    url: https://github.com/SoftingIndustrial/SDEXapi
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: 0
  script:
    - git config --global user.name "GitLab CI"
    - git config --global user.email "ci@example.com"
    - git remote add github https://x-access-token:${GITHUB_TOKEN}@github.com/SoftingIndustrial/SDEXapi.git
    - git fetch origin "+refs/heads/*:refs/heads/*" --prune
    - git push github --all
    - git push github --tags
    
